# Generated by Django 4.2.4 on 2023-09-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTravel', '0003_alter_travel_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='cities',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='travel',
            name='country',
            field=models.CharField(max_length=25),
        ),
    ]
