# Generated by Django 4.2.4 on 2023-09-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTravel', '0005_alter_messages_message_alter_tours_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='subject',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
